export const CROP_FRESH_TYPES = [
  "Groundnut pods(raw)",
"Paddy(Common)",
"Tomato",
"Bengal Gram(Gram)(Whole)",
"Lemon",
"Beans",
"Jaggery",
"Sunflower Seed",
"Bengal Gram Dal(Chana Dal)",
"Onion",
"Cabbage",
"Maize",
"She Goat",
"Green Gram Dal (Moong Dal)",
"Karbuja(Musk Melon)",
"Orange",
"Arhar(Tur/Red Gram)(Whole)",
"Cluster beans",
"Cauliflower",
"Cotton",
"Cauliflower",
"Cotton",
"Arhar (Tur/Red Gram)(Whole)",
"Mango",
"Mousambi(Sweet Lime)",
"Rice",
"Black Gram Dal (Urd Dal)",
"Paddy(Dhan)(Basmati)",
"Black Gram Dal(Urd Dal)",
"Red Gram",
"Onion",
"Cabbage",
"Maize",
"She Goat",
"Green Gram Dal (Moong Dal)",
"Karbuja(Musk Melon)",
"Orange",
"Arhar(Tur/Red Gram)(Whole)",
"Sunflower",
];
