export const CROP_FRESH_TYPES = [
  "Ajwan",
  "Arhar (Tur/Red Gram)(Whole)",
  "Arhar(Tur/Red Gram)(Whole)",
  "Bajra(Pearl Millet/Cumbu)",
  "Banana",
  "Beans",
  "Beetroot",
  "Bengal Gram Dal (Chana Dal)",
  "Bengal Gram Dal(Chana Dal)",
  "Bengal Gram(Gram)(Whole)",
  "Black Gram (Urd Beans)(Whole)",
  "Black Gram Dal (Urd Dal)",
  "Black Gram Dal(Urd Dal)",
  "Black Gram(Urd Beans)(Whole)",
  "Bottle gourd",
  "Brinjal",
  "Cabbage",
  "Cashewnuts",
  "Castor Seed",
  "Cauliflower",
  "Chili Red",
  "Cluster beans",
  "Cotton",
  "Dry Chillies",
  "Foxtail Millet(Navane)",
  "Green Chilli",
  "Green Gram Dal (Moong Dal)",
  "Ground Nut Oil",
  "Ground Nut Seed",
  "Groundnut",
  "Gur(Jaggery)",
  "Jaggery",
  "Jowar(Sorghum)",
  "Karbuja(Musk Melon)",
  "Kulthi(Horse Gram)",
  "Lemon",
  "Lime",
  "Maize",
  "Mango",
  "Mousambi(Sweet Lime)",
  "Onion",
  "Orange",
  "Paddy(Dhan)(Basmati)",
  "Paddy(Dhan)(Common)",
  "Papaya",
  "Potato",
  "Raddish",
  "Ragi (Finger Millet)",
  "Red Gram",
  "Ridgeguard(Tori)",
  "Rice",
  "Sesamum(Sesame,Gingelly,Til)",
  "She Goat",
  "Soyabean",
  "Sunflower",
  "Sunflower Seed",
  "Sweet Potato",
  "Tamarind Fruit",
  "Tamarind Seed",
  "Tomato",
  "Turmeric",
  "Turmeric (raw)",
  "Water Melon",
  "Wood"
];
