export const MARKETS = [
"anaganapalli",
"Pattikonda",
"Rajahmundry",
"Atmakur",
"Sampara",
"Yemmiganur",
"Ipur",
"Tadikonda",
"Jaggayyapeta",
"Dharmavaram",
"Kakinada",
"Palamaner APMC",
"Eluru APMC",
"Chintapally APMC",
"Anantapur APMC",
"Adoni",
"Rajampet",
"Hindupur","Karapa",
"Eluru",
"Nellore",
"Ambajipeta APMC",
"Denduluru APMC",
"Punganur APMC",
"Guntur APMC",
    "Tirupati APMC",
    "Paderu",
"Nandyal APMC",
"Ravulapelem APMC",
"Anakapally APMC",
"Madanapalli APMC",
"Tenali",
"Adoni",
"Rajampet",
"Hindupur",
"Karapa",
"Eluru",
"Nellore",
"Ambajipeta APMC",
"Denduluru APMC",
"Punganur APMC",
"Guntur APMC",
"Jaggampet APMC",
"Vepanjari APMC",
"Rompicherla APMC"
]